import React from 'react'

function Termsandconditions() {
    return (
        <div className='container mb-5'>
            <div className='row text-center border-bottom p-5'>
                <h1 className='mt-5 fs-3 p-5'>Terms and conditions</h1>
            </div>
            <div className='row mt-2 copy'>
                <h4>Zerodha</h4>
               <p>In the course of using this website or any of the websites under the ‘Zerodha’ domain or availing the products and services vide the online application forms and questionnaires, online consents and such other details required from time to time on any of Zerodha’s (and/or its affiliates) web platforms or mobile applications, Zerodha and/or its affiliates may become privy to some of Your personal information, including which may or may not be of confidential nature. Zerodha is strongly committed to protecting the privacy of its users/clients and has taken all necessary and reasonable measures to protect the confidentiality of any customer information.</p>
               <p>For the purpose of these Privacy Policy, wherever the context so mentions “Covered Persons”, "Client","You" or "Your”, it shall mean any natural or legal person who has visited this website/platform and/or has agreed to or has enquired open an account and/or initiated the process of opening an account with Zerodha (also defined as “Covered Persons”).</p>
               <p>Zerodha allows any person to use/visit/browse the website without registering on the website. The term "We", "Us" , "Our" and "Team Zerodha" shall mean Zerodha Broking Limited. Zerodha Broking Limited and/or Zerodha Commodities Pvt. Ltd. (hereinafter shall be referred together as ‘Zerodha’). Zerodha Broking Limited is a Trading Member of NSE and BSE, registered with Securities & Exchange Board of India ("SEBI") and having Registration No. INZ000031633. This website is owned, operated and maintained by Zerodha Broking Limited, a Company incorporated under the Companies Act, 2013 having CIN: U65929KA2018PLC116815, and having its Registered Office at #153/154, 4th Cross, Dollars Colony, JP Nagar 4th Phase, Bangalore - 560078. Access to Your Zerodha account and the usage of Your account is subject to Your compliance with all the terms and conditions set forth herein, read along with all documents, including but not limited to; applications forms and undertakings, signed by you during account opening, and any terms/consents/policies included on Zerodha’s website/domain, i.e. https://zerodha.com/, including its “Terms and Conditions”, “Policies & Procedures”, and “Disclosure”.</p>
                <h4>Scope of this Policy</h4>
                <p>Any natural or legal person who has visited the Zerodha website/platform and/or the mobile application, and/or who may or may not have further agreed to initiate the process of opening an account with Zerodha shall come under the purview of the scope of this Privacy Policy. Zerodha shall at all times follow all such rules prescribed under the Information Technology Act, 2000, and rules & procedural guidelines set by the Securities Exchange Board of India (“SEBI”) and/or any of its regulated entities/intermediaries that Zerodha is a member of.</p>
                <h4>Collection and use of your personal information</h4>
                <p>Zerodha may or may not collect your Personal Information to provide services on its web based platform or mobile application. While opening a trading and demat account with Zerodha, you may be asked for certain Sensitive Personal Data or Information (as defined under the Information Technology Act, 2000) to complete your KYC (as per the ‘Know Your Client’ requirements set by SEBI) and as per the Prevention of Money Laundering Act, 2002.</p>
                <p>Zerodha, may or may not, request for sensitive information from You at the time of account opening, which would include but not be limited to, (i) setting a password; (ii) financial information such as Bank account or credit card or debit card or other payment instrument details; (iii) information such as name, contact number, gender, date of birth, residence and employment addresses, father’s/mother’s and spouses names, bank account details, scans/copies of document proofs of address & identity such as Photograph, PAN, passport, drivers license, Aadhaar (voluntarily) etc. (iv) uploading signature proof/photo etc. All such information would be for the purpose of: identity verification and background checking for account opening as per KYC & AML Rules, personalising services offered to you, keeping you updated of our products and services relevant to you, information pertaining to our services you’ve subscribed to, and for any legal and regulatory / audit purposes.</p>
                <p>Under Regulation 5 of the Information Technology (Reasonable Security and Procedures and Sensitive Personal Data or Information) Rules, 2011, Zerodha is obliged to provide every registered user of Zerodha with a readable copy of the personal information you have provided us.</p>
                <p>We would save such information as required by the law, and as directed by the regulators along with such intermediaries regulated by them, for the purpose of offering You our services, and for such further regulatory, audit, and business purposes. We collect Personal Information from you only when you voluntarily use the services provided by Zerodha, and/or enquire to begin an association with Zerodha and/or complete the process of opening an account with Zerodha.</p>
                <p>With regard to security, we respect all information provided to us, and take all reasonable steps towards protection of the same. We have implemented technology and policies, with the objective of protecting your privacy from unauthorized access and improper use, and periodically review the same. We maintain procedural safeguards to protect the confidentiality and security of personally identifiable information transmitted to us.</p>
                <h4>Aadhaar user consent policy</h4>
                <h4>Voluntary Act</h4>
                <p>The act of providing your Aadhaar is voluntary in nature, which will only be required for completing your account opening procedure online and for digitally signing the Zerodha account opening form. Your Aadhaar may also be used as a proof of address as an alternative choice to drivers license or Passport copy, which is a voluntary decision to be made by You.</p>
                <p>You may alternatively choose to go through the offline route of account opening by physically signing all such account opening documents, which does not require you to share your Aadhaar information at all.</p>
                <h4>Zerodha does not store any Aadhaar information</h4>
                <p>During your online account opening process, you do not input any Aadhaar details on the Zerodha platform. You would be issuing your Digital Aadhaar to Digilocker, from where Zerodha (Zerodha is registered as a Requester on the Digilocker platform) would receive information, based on your consent to allow Digilocker to share such information with Zerodha, limited to: (1) The last four digits of your Aadhaar / VID (Virtual ID created on the UIDAI website), (2) Full Name, (3) Date of Birth, (4) Gender, (5) Address, and (6) Your Photo.</p>
                <p>Digilocker is a part of the National eGovernance Division under the Ministry of Electronics & Information Technology (MeitY), Government of India. The Digital Aadhaar issued within DigiLocker is the same as the eAadhaar issued by UIDAI (https://eaadhaar.uidai.gov.in). DigiLocker has partnered with UIDAI to make it available automatically to its users when they link their DigiLocker account with Aadhaar. This act of issuing an eAadhaar within Digilocker and subsequently Digilocker sharing the information limited to the above points, leads to behaving as a physical KYC. Zerodha only receives information limited to the above points for the purposes of completing KYC of clients online.</p>
                <p>All clients may alternatively follow the offline route of account opening, which does not require sharing any Aadhaar related information.</p>
                <p>During your online account opening process, you would also be sharing your Aadhaar with Digiotech Solutions Pvt. Ltd. for the purpose of digitally signing the Zerodha account opening form. Digiotech Solutions Pvt. Ltd. does not share your Aadhaar with Zerodha. After the account opening form has been digitally signed by you, a copy of the digitally signed form would be emailed to you and to Zerodha for reference/audit purposes. Digiotech Solutions Pvt. Ltd. is a licensed e-Sign ASP (Application Services Provider) with CDAC, compliant with the guidelines laid down by the Controller of Certifying Authorities (CCA), India and UIDAI, to enable you to eSign the account opening forms online.</p>
        </div>
        </div>
    );
}

export default Termsandconditions;